services:
  backend:
    volumes:
      - ../app/backend-bun/src:/app/src
    command: bun --hot run /app/src/server.ts

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../app/frontend/src:/app/src
    environment:
      VITE_API_BASE: http://localhost:8000
